name: Automatic Deployments 

on:
  push:
    branches:
      - main

concurrency:
  group: automatic_deploy

permissions:
  # Both of these are required for aws-actions/configure-aws-credentials@v4
  id-token: write
  contents: read
  # The packages & actions are required for check-artifact
  packages: read
  actions: read

jobs:
  check_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Get current commit SHA
        id: get-current-sha
        run: |
          echo "deploy_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Check for changes
        id: check-changes
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Triggered by workflow dispatch. Continuing."
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          elif [ "${{ steps.get-current-sha.outputs.deploy_sha }}" == "$SSM_DEPLOY_SHA" ]; then
            echo "No changes detected. Exiting."
            echo "changes_detected=true" >> $GITHUB_OUTPUT
            # exit 0
          else
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi

      - name: Get Changed Files
        id: get-changed-files
        # if: ${{ steps.check-changes.outputs.changes_detected == 'true' }}
        run: |
          echo "Current commit SHA: ${{ steps.get-current-sha.outputs.deploy_sha }}"

          CHANGED_FILES=$(git diff --name-only $SSM_DEPLOY_SHA HEAD)
          echo "Changed files:"
          echo "$CHANGED_FILES"

          printf "changed-files<<EOF\n$CHANGED_FILES\nEOF\n" >> $GITHUB_OUTPUT

    outputs:
      changes_detected: ${{ steps.check-changes.outputs.changes_detected }}
      deploy_sha: ${{ steps.get-current-sha.outputs.deploy_sha }}
      changed_files: ${{ steps.get-changed-files.outputs.changed-files }}

  debug_logs:
    runs-on: ubuntu-latest
    needs: [check_changes]

    steps:
      - name: Log Changed Apps
        run: |
          echo "Deploy Sha: "
          echo "${{ needs.check_changes.outputs.deploy_sha }}"
          echo "Changed Files: "
          echo "${{ needs.check_changes.outputs.changed_files }}"



