name: Consumer Workflow

on:
  workflow_run:
    workflows: ["Build and Deploy DEVELOP"]
    types:
      - completed

jobs:
  use-output:
    runs-on: ubuntu-latest
    steps:
      - name: Print output from previous workflow
        run: echo "Received:" + ${{ github.event.workflow_run.outputs.my_variable }}
